services:
  server:
    build:
      context: .
    ports:
      - "7000:80"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
