services:
  server:
    build:
      context: .
      target: dev
    ports:
      - "7000:80"
    volumes:
      - type: bind
        source: .
        target: /app
  postgres:
    image: postgres:16.4
    shm_size: "1gb"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 7020:8080
  seq:
    image: datalust/seq:latest
    environment:
      SEQ_API_CANONICALURI: http://seq
      ACCEPT_EULA: 'Y'
    ports:
      - 2000:80
      - 5341:5341
    volumes:
      - seq_data:/data

volumes:
  postgres:
  seq_data:
