@url = http://server:80
@reservation_id = 5c06971f-b821-46ce-8e03-76ec2680f9ec
@spot_id = 00000000-0000-0000-0000-000000000004

@user_id = 9c671f80-74b5-411a-b802-fbd2fbfca799


###

GET {{url}}/users

###
GET {{url}}/users/{{user_id}}

###

POST {{url}}/users
Content-Type: application/json

{
    "email": "user1@test.com",
    "username": "user1",
    "password": "secret",
    "fullName": "John Doe",
    "role": "user"
}

### 
GET {{url}}/parking-spots
Accept: application/json

###
POST {{url}}/parking-spots/{{spot_id}}/reservations/vehicle
Content-Type: application/json

{
    "employeeName": "Mark Doe",
    "licensePlate": "plate",
    "date": "2024-09-26",
    "capacity": "1"
}
###
POST {{url}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
    "date": "2024-09-22"
}

###
PUT  {{url}}/parking-spots/reservations/{{reservation_id}}
Content-Type: application/json

{

    "licensePlate": "NePlate"

}

###
DELETE   {{url}}/parking-spots/reservations/{{reservation_id}}

###
DELETE http://server/reservations/0a4cd397-dec6-403d-b925-3c413561eb86

###
GET http://server/reservations/7064d68c-6808-431c-a311-370415253b4c